FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install production dependencies only
RUN npm install --legacy-peer-deps --production

# Copy pre-built dist folder
COPY dist ./dist

EXPOSE 3002

CMD ["node", "dist/main.js"]
